### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by ghost** [mfdavid/edueditor#3]
Use properties of Javascript to create short cuts as F5 ( Execute ), F9 ( Compile / Interpreter and run ), CTRL + ], CTRL + [ ... this implementation can be util for programmers. - Also clear the screen.

**Comment by marciofrayze** [comment]
Thanks for your feedback!
I cannot use F5 or F9 as shortcuts since they are already used in the browsers (e.g. F5 is used to reload the page).
The current version does have one shortcut to run the programs: ALT + R. But it is not working properly on Macs (it prints a weird character before trying to execute the code). It works on Linux (haven't tested on Windows yet).

I'll fix that and implement more shortcuts in the next version. Will keep this issue open until then.

**Comment by ghost** [comment]
Cool, or buttons at place of shortcuts. ( By the way, great design - clean )
